plugins:
  editorconfig:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  cppcheck:
    enabled: true
  gnu-complexity:
    enabled: true
    config:
      threshold: 100
