name: Development CI

on:
  push:
    branches:
      - development

jobs:
  linux:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: update ${{ matrix.os }}
      run: |
        sudo apt-get update
        sudo apt-get install build-essential clang-tools-9 libc++-9-dev libc++1-9 libc++abi-9-dev libc++abi1-9
    - name: update ${{ matrix.os }}
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.14.1'
    - name: configure on ${{ matrix.os }}
      env:
        CC: clang-9
        CXX: clang++-9
        CI: true
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=ON
    - name: build on ${{ matrix.os }}
      run: cmake --build build

  macos:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: update ${{ matrix.os }}
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.14.1'
    - name: configure on ${{ matrix.os }}
      env:
        CI: true
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=ON
    - name: build on ${{ matrix.os }}
      run: cmake --build build

  windows:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: update ${{ matrix.os }}
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.14.1'
    - name: configure on ${{ matrix.os }}
      env:
        CI: true
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=ON
    - name: build on ${{ matrix.os }}
      run: cmake --build build
