name: Master CI

on:
  push:
    branches:
      - master

jobs:
  linux:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: update ${{ matrix.os }}
      run: |
        sudo apt-get update
        sudo apt-get install build-essential
    - name: configure on ${{ matrix.os }}
      env:
        CC: gcc-9
        CXX: g++-9
        CI: true
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - name: build on ${{ matrix.os }}
      run: cmake --build build

  macos:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: configure on ${{ matrix.os }}
      env:
        CI: true
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - name: build on ${{ matrix.os }}
      run: cmake --build build

  windows:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: configure on ${{ matrix.os }}
      env:
        CI: true
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - name: build on ${{ matrix.os }}
      run: cmake --build build
