name: Master CI

on:
  push:
    branches:
      - master

jobs:
  linux:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: update ${{ matrix.os }}
      run: |
        sudo apt-get update
        sudo apt-get install build-essential qtbase5-dev clang-tools-9
    - name: configure on ${{ matrix.os }}
      env:
        CC: gcc-9
        CXX: g++-9
        CI: true
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON
    - name: build on ${{ matrix.os }}
      run: cmake --build build

  macos:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: update ${{ matrix.os }}
      run: |
        brew install qt5
        echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.bash_profile
    - name: configure on ${{ matrix.os }}
      env:
        CI: true
        LDFLAGS: -L/usr/local/opt/qt/lib
        CPPFLAGS: -I/usr/local/opt/qt/include
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_PREFIX_PATH=$(brew --prefix qt5)
    - name: build on ${{ matrix.os }}
      run: cmake --build build
